# Generated by Django 4.2.4 on 2023-08-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_produkt_blandningen_produkt_bredd_produkt_färg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='blandningen',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='bredd',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='färg',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='vikt',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='yta',
        ),
    ]
