# Generated by Django 4.2.4 on 2023-08-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_produkt_blandningen_remove_produkt_bredd_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produkt',
        ),
    ]
