# Generated by Django 4.2.4 on 2023-08-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_produkt'),
    ]

    operations = [
    ]
