# Generated by Django 4.2.4 on 2023-08-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20230803_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='bredd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='vikt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
