# Generated by Django 4.2.4 on 2023-08-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_produkt_bredd_alter_produkt_vikt'),
    ]

    operations = [
    ]
