# Generated by Django 4.2.4 on 2023-08-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20230803_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produkt',
            options={'ordering': ('-skapad',)},
        ),
    ]
