# Generated by Django 4.2.4 on 2023-08-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_category_options_alter_produkt_options_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='inventory',
            field=models.IntegerField(default=0, help_text='Mängd tyg kvar'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Är denna produkt i lager?'),
        ),
    ]
