# Generated by Django 4.2.4 on 2023-08-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_produkt_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='blandning',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='färg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='kvalitet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='motiv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
