# Generated by Django 4.2.4 on 2023-08-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_produkt_blandning_alter_produkt_färg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='inventory',
            field=models.IntegerField(default=0, help_text='Mängd kvar i lager'),
        ),
    ]
