# Generated by Django 4.2.4 on 2023-08-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_produkt_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='unit',
            field=models.CharField(choices=[('m', 'Meter'), ('st', 'St')], default='st', help_text='Enhet för denna produkt', max_length=4),
        ),
    ]
