# Generated by Django 4.2.4 on 2023-08-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_produkt_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='is_fabric',
            field=models.BooleanField(default=False, help_text='Är denna produkt ett tyg?'),
        ),
    ]
