# Generated by Django 4.2.4 on 2023-11-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_produkt_is_fabric'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='discount_percentage',
            field=models.IntegerField(blank=True, default=0, help_text='Rabatt i procent', null=True),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='inventory',
            field=models.IntegerField(default=0, help_text='Mängd kvar i lager, st eller decimeter'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='pris',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
