# Generated by Django 4.2.4 on 2023-11-07 13:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_produkt_discount_percentage_alter_produkt_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='beskrivning',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
