# Generated by Django 4.2.4 on 2023-12-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20231118_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='is_stubbie',
            field=models.BooleanField(default=False, help_text='Markera om denna produkt är en stuvbit.'),
        ),
    ]
