# Generated by Django 4.2.4 on 2023-12-18 14:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_produkt_is_stubbie'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='image2',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Valfri: Lägg till en andra bild av produkten.', max_length=255, null=True, verbose_name='image2'),
        ),
    ]
