# Generated by Django 4.2.4 on 2024-01-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_rename_name_subcategory_namn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
