# Generated by Django 4.2.4 on 2024-01-22 12:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_washinstruction_produkt_wash_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washinstruction',
            name='icon',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='icon'),
        ),
    ]
