# Generated by Django 4.2.4 on 2024-01-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_color_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='allow_custom_text',
            field=models.BooleanField(default=False),
        ),
    ]
