# Generated by Django 4.2.4 on 2024-08-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_productvariant_allow_custom_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='is_bmb_exclusive',
            field=models.BooleanField(default=False, help_text='Är denna produkt BMB exklusiv?'),
        ),
    ]
