# Generated by Django 5.2.17 on 2026-08-18 22:16

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_produkt_is_bmb_exclusive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='beskrivning',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
