# Generated by Django 4.2.4 on 2024-02-01 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_productvariant_allow_custom_text'),
        ('order', '0003_order_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.color'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
